name: HC
version: '1.0-SNAPSHOT'
main: xryzo11.hC.HC
api-version: '1.21'
commands:
  hc:
    description: Main command. Use "/hc help"
permissions:
  hc.command:
    description: Allows the player to use the HC command
    default: op
  hc.command.locator:
    description: Allows the player to use the locator subcommand
    default: op
  hc.command.config:
    description: Allows the player to use the config subcommand
    default: op
  hc.command.help:
    description: Allows the player to use the help subcommand
    default: op
  hc.command.sidelocator:
    description: Allows the player to use the side locator subcommand
    default: op